### ISSUE TITLE
About mean_std.npy

### ISSUE THREAD

**Issue by Alanzhang92** [huiqu18/FullNet-varCE#1]
Hello, I'm very interest in your work. When I tried to run train.py, it remind me that I need to provide mean_td.npy for both train and test. However, I can't find this file in this project. I think you maybe forget to add it in your project?

**Comment by huiqu18** [comment]
Sorry for the late reply. 
The mean_std.py is computed using the images in the training set.

**Comment by thinkInJava33** [comment]
sorry, Could you please provide the file

**Comment by thinkInJava33** [comment]
sorry, Could you please provide the file or the values of mean and std

> Sorry for the late reply.
> The mean_std.py is computed using the images in the training set.
sorry, Could you please provide the file

**Comment by MegumiOuO** [comment]
> sorry, Could you please provide the file or the values of mean and std
> 
> > Sorry for the late reply.
> > The mean_std.py is computed using the images in the training set.
> > sorry, Could you please provide the file

this is the mean_std value calculated by myself，you can use it.
normalize: [[0.78780321 0.5120167  0.78493782],
                       [0.16766301 0.24838048 0.13225162]]

**Comment by thinkInJava33** [comment]
> > sorry, Could you please provide the file or the values of mean and std
> > > Sorry for the late reply.
> > > The mean_std.py is computed using the images in the training set.
> > > sorry, Could you please provide the file
> 
> this is the mean_std value calculated by myself，you can use it.
> normalize: [[0.78780321 0.5120167 0.78493782],
> [0.16766301 0.24838048 0.13225162]]

thank you,but i still got some probleams,i want to  train the model on GlaS.But errors occured,like--
FileNotFoundError: [Errno 2] No such file or directory: './data/GlaS/weight_maps/train' 
do you know how  to handle the dataset so that i can run train.py without error.

**Comment by MegumiOuO** [comment]
> > > sorry, Could you please provide the file or the values of mean and std
> > > > Sorry for the late reply.
> > > > The mean_std.py is computed using the images in the training set.
> > > > sorry, Could you please provide the file
> > 
> > 
> > this is the mean_std value calculated by myself，you can use it.
> > normalize: [[0.78780321 0.5120167 0.78493782],
> > [0.16766301 0.24838048 0.13225162]]
> 
> thank you,but i still got some probleams,i want to train the model on GlaS.But errors occured,like--
> FileNotFoundError: [Errno 2] No such file or directory: './data/GlaS/weight_maps/train'
> do you know how to handle the dataset so that i can run train.py without error.

this code could use the weight map to improve the results, and the code for calculating weight map is provided (weight_map.m). You can use this code to calculate it, the input data is anno of the img.

**Comment by thinkInJava33** [comment]
> > > > sorry, Could you please provide the file or the values of mean and std
> > > > > Sorry for the late reply.
> > > > > The mean_std.py is computed using the images in the training set.
> > > > > sorry, Could you please provide the file
> > > 
> > > 
> > > this is the mean_std value calculated by myself，you can use it.
> > > normalize: [[0.78780321 0.5120167 0.78493782],
> > > [0.16766301 0.24838048 0.13225162]]
> > 
> > 
> > thank you,but i still got some probleams,i want to train the model on GlaS.But errors occured,like--
> > FileNotFoundError: [Errno 2] No such file or directory: './data/GlaS/weight_maps/train'
> > do you know how to handle the dataset so that i can run train.py without error.
> 
> this code could use the weight map to improve the results, and the code for calculating weight map is provided (weight_map.m). You can use this code to calculate it, the input data is anno of the img.

Iteration: [0/11]	Loss 0.0013	Loss_CE 0.0013	Loss_var 0.0000	Pixel_Accu 0.9491	IoU 0.0000
2019-10-26 03:53		=> Train Avg: Loss 0.0037	Loss_CE 0.0037	Loss_var 0.0000	Pixel_Accu 0.9559	IoU 0.0000
2019-10-26 03:54		=> Val Avg:   Loss 0.0000	Pixel_Acc 1.0000	IoU 0.0000
thank you for your help,i can finally train without errors,but do you know why the metrics except pixel_accu is always zero,this is a part my traning logs.And it the same problem with test.

**Comment by Megumi-cs** [comment]
@thinkInJava33  i'm not very sure for your problem. you should make the input labels only contain 0,1（0 for background and 1 for gland） or 0,255. it means you cant use GlaS‘s anno directly. maybe you dont take this operation

**Comment by thinkInJava33** [comment]
> > sorry, Could you please provide the file or the values of mean and std
> > > Sorry for the late reply.
> > > The mean_std.py is computed using the images in the training set.
> > > sorry, Could you please provide the file
> 
> this is the mean_std value calculated by myself，you can use it.
> normalize: [[0.78780321 0.5120167 0.78493782],
> [0.16766301 0.24838048 0.13225162]]

sorry to bother you again,do you know how to get the mutil organ dataset
