### ISSUE TITLE
About the mean_std.npy file

### ISSUE THREAD

**Issue by 1006YuxinKang** [huiqu18/FullNet-varCE#10]
Thanks for sharing the codes. I trained the code for the segmentation of The MICCAI 2015 gland segmentation challenge dataset (GlaS). But I trained the model without the mean_std.npy, Could you share the file of both 2 dataset? Thank you!

**Comment by 1006YuxinKang** [comment]
@huiqu18

**Comment by huiqu18** [comment]
@1006YuxinKang 
GlaS:  [[0.78780321 0.5120167  0.78493782], [0.16766301 0.24838048 0.13225162]]
MultiOrgan:  [[0.74408994 0.53806349 0.66497889], [0.15811703 0.19705941 0.15046222]]

**Comment by 1006YuxinKang** [comment]
> @1006YuxinKang
> GlaS: [[0.78780321 0.5120167 0.78493782], [0.16766301 0.24838048 0.13225162]]
> MultiOrgan: [[0.74408994 0.53806349 0.66497889], [0.15811703 0.19705941 0.15046222]]

Thank you！sir！
