### ISSUE TITLE
The model tar file  can't open

### ISSUE THREAD

**Issue by liucunzhuang** [huiqu18/FullNet-varCE#11]
I download your model tar file, and I unzip this file, however  it shows damaged

**Comment by huiqu18** [comment]
@liucunzhuang You don't need to upzip the model tar file. The model weights can be loaded as follow:
https://github.com/huiqu18/FullNet-varCE/blob/9c654293e9359f6b245ba955d3151477fa5ae2c0/train.py#L85-L88
where `opt.train['checkpoint']` is the path to the model tar file.
