### ISSUE TITLE
Request for help of labels_instance images

### ISSUE THREAD

**Issue by rocketche** [huiqu18/FullNet-varCE#13]
Thanks for sharing! I'm really interested in this project but I encountered some problems in duplicating the code. You've said that:

> For MultiOrgan dataset, generate the instance labels from the .xml annotation files. Use uint16 instead of uint8 to assign a unique integer for each nucleus.

I ran the code downloaded from https://drive.google.com/file/d/0ByERBiBsEbuTRkFpeHpmUENPRjQ/view, and I got images from the .xml files. Like that:
![TCGA-18-5592-01Z-00-DX1](https://user-images.githubusercontent.com/54346468/97983192-e0cff580-1e0f-11eb-8abf-e1ea0260e441.png)
TCGA-18-5592-01Z-00-DX1.png

If I directly run weight_map.m using these images, the output is unsatisfied. Like this:
![TCGA-18-5592-01Z-00-DX1_weight](https://user-images.githubusercontent.com/54346468/97983418-3e644200-1e10-11eb-89aa-8115edde3cb7.png)

And I found that the the value of label-instance images didn't have much intergers(only have 0, 32896, 65535). Like this:
![2020-11-05_103453](https://user-images.githubusercontent.com/54346468/98191020-44af0700-1f53-11eb-8f57-d79df2b598a8.png)

Therefore, I think this is because I ignored ①**Use uint16 instead of uint8** ② **assign a unique integer for each nucleus**.

Am I right with my analysis? Would you like to share the code of this step(① and ②) or share some hints of this step? Thank you very much.

P.S. the ternary-label images are fine so far but the weight-map images are not right as you can see.

**Comment by huiqu18** [comment]
@rocketche In the online code to generate labels from .xml files (`create_maps.m`), add a nuclei mask to assign each nucleus a unique integer `mask_nuclei(t>0) = zz` in the for loop starting from Line 65. Then save this `mask_nuclei` as uint16, which is the instance label I used in my code.

**Comment by rocketche** [comment]
@huiqu18 Thank you very much!
