### ISSUE TITLE
Hi, I think Glas dataset has also changed

### ISSUE THREAD

**Issue by weiaicunzai** [huiqu18/FullNet-varCE#14]
Now, Glas dataset have 85 training images, 60 testA images, instead of 80 for training, 65 for testA, as you mentioned in paper.
>The MICCAI 2015 gland segmentation challenge dataset (GlaS) [12] consists of 165 images that come from 16 H&E stained histological sections of colorectal adenocarcinoma.They are separated into train, testA and testB parts, containing 80, 65 and 20 images, respectively. Train and testA parts have both benign and malignant cases, while testB set is mostly malignant cases.

**Comment by huiqu18** [comment]
@weiaicunzai Sorry, I just noticed that it was a mistake in the paper. There are 85 for training and 60 for test A in the GlaS.

**Comment by weiaicunzai** [comment]
> @weiaicunzai Sorry, I just noticed that it was a mistake in the paper. There are 85 for training and 60 for test A in the GlaS.

Ok, then, thanks for your reply.
