### ISSUE TITLE
Hi, can we train fullnet with a larger input image size?

### ISSUE THREAD

**Issue by weiaicunzai** [huiqu18/FullNet-varCE#15]
Thanks for your great work. I've tried to train fullnet using a larger input image size, e.g. 473x473, but always gives me cuda out of memory error, Im using a 3090 (24gb memory), I just want to make sure that if we can train fullnet with a much larger input image size like 512 x 512  or not, thanks.

**Comment by huiqu18** [comment]
@weiaicunzai The training of fullnet does require a lot of memory which is a major drawback. It is impossible to train with images with 512x512, unless you reduce the number of layers in each block.
