### ISSUE TITLE
Where can I find the mean_std.npy file for image normalization?

### ISSUE THREAD

**Issue by Jiangbo-Shi** [huiqu18/FullNet-varCE#16]

**Comment by huiqu18** [comment]
GlaS: [[0.78780321 0.5120167 0.78493782], [0.16766301 0.24838048 0.13225162]]
MultiOrgan: [[0.74408994 0.53806349 0.66497889], [0.15811703 0.19705941 0.15046222]]

You can compute the mean and std if using your own datasets.
