### ISSUE TITLE
About Results

### ISSUE THREAD

**Issue by Alanzhang92** [huiqu18/FullNet-varCE#2]
Excuse me, due to there's something wrong with weight map that I provide for training, I try to train this network in GlaS without weight maps and get  lower results with your paper. The main differences are in testA, I only get a score 0.870 for F1, 0.893 for Dice obj and 49.56 for Hausdorff obj. 

So I want to know more details about your work, such as the process of generating weight maps（because when I training with my weight maps，I got all scores become 0 at last.It must be something wrong in my function)   and how to set train/val training sets.

**Comment by huiqu18** [comment]
Sorry for the late reply. The weight maps can help to promote performance. I have released the code of computing weight maps.
