### ISSUE TITLE
 No such file or directory: './data/MultiOrgan/mean_std.npy'

### ISSUE THREAD

**Issue by Acmenwangtuo** [huiqu18/FullNet-varCE#5]
When I run the code, i don't know how i can get the file "mean_std.npy",should it a value set by myself?

**Comment by huiqu18** [comment]
It is the mean and standard deviation values of the images in the training set.  The values for Multi-Organ dataset I used were mean=[0.7441, 0.5381, 0.6650], std=[0.1581, 0.1971, 0.1505]. They may be different depending on what color normalization method you do on the dataset.
