### ISSUE TITLE
Request for Help

### ISSUE THREAD

**Issue by naumanbashir70** [huiqu18/FullNet-varCE#7]
![err](https://user-images.githubusercontent.com/58822992/78720855-e4fe6800-793f-11ea-85c4-e21bbe39904b.jpeg)

Hi @huiqu18  could you help me in executing the source code, I am receiving this ( see attachment). Directories are created but there is no patches and weights .

**Comment by huiqu18** [comment]
@naumanbashir70 The file_list seems to be empty. You can check the paths of original images, labels and weight maps to make sure that they are all correct.
