### ISSUE TITLE
Results on Kumar Dataset

### ISSUE THREAD

**Issue by tabibusairam** [huiqu18/FullNet-varCE#9]
I'm trying to replicate the results on Kumar Dataset based on the **pretrained model** you provided, but the AJI is coming out to be 0.1 less than the reported number.
I'm putting the steps which i followed, please let me know where I'm going wrong.

1. For the images, I took the instance labels and stain normalized images from the drive link you posted. ( 1000x1000).
2. Used weight_map.m to calculate the weight-maps from the instance labels and used the split_patches in prepare_data.py method to split them.
3. I used prepare_data.py  to get the ternary label images ( 250x250 - 16 images per 1000x1000 image ).
4. I also divided the instance labels into 250x250 patches with the nuclei numbering in them as they are using split_patches in prepare_data.py. 
5. I calculated the mean and std from the training patches ( 250*250 ) - they came out to be - [0.742977   0.52264721 0.64587741 0.16154773 0.16746429 0.13173944] stored them in a **2x3 numpy array**.
6. I used the instance label 250*250 patches as GT in testing.
7. I then used test.py to get the results. 
 I'm not sure where I'm going wrong or is there any parameter that I need to adjust. Please help.

**Comment by tabibusairam** [comment]
Also I tried it using the 1000x1000 images and instance label with the pretrained model all which were uploaded on this git. But the AJI still comes very low.

**Comment by huiqu18** [comment]
@tabibusairam For testing, the input and label are the original 1000x1000 image and 1000x1000 instance label. You don't need to split them into small patches.
Not sure if you used the original Kumar dataset. They replaced several images later. If you use the color normalized images in this folder https://drive.google.com/drive/folders/1JEhmbOZ2R9kz4kCJknCpV7sjiZ2w0diR, you should be able to obtain the reported numbers.
